eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8480/eureka/
server:
  port: 8580

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanwei1995/configuration/
          searchPaths: boot
          # 对于使用git,svn做为后端配置，从远程库获取配置文件，需要存储到本地文件
          basedir: /tmp/spring-cloud-repo
          # 配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true
  application:
    name: config-server